const GameActionTypes = {
  SET_CURRENT_GAME: 'SET_CURRENT_GAME',
  SET_BOARD_MESSAGE: 'SET_BOARD_MESSAGE',
  SET_MY_TURN: 'SET_MY_TURN',
  TOGGLE_IS_PLAYING: 'TOGGLE_IS_PLAYING',
  SET_TIMER: 'SET_TIMER',
  TOGGLE_ACTION_BUTTONS: 'TOGGLE_ACTION_BUTTONS',
  TOGGLE_IS_BLURRED: 'TOGGLE_IS_BLURRED',
};

export default GameActionTypes;
